### ISSUE TITLE
Apply Bugfixes

### ISSUE THREAD

**Issue by vulcandth** [vulcandth/pokecrystal16#3]
### \<Unsure which commit to merge these into>

*   [x] aaaaaa123456789/pokecrystal16#6
*   [x] aaaaaa123456789/pokecrystal16#9 and the increase in code size from 16-bit support, it might be worthwhile to strip out leftover mobile code, leaving only what's necessary for the Battle Tower

### **Add Pokémon conversion table functions**

*   [x] aaaaaa123456789/pokecrystal16#7 Replace `wBreedMon1` with `wBreedMon1Species` in garbage collection.

### **Update remaining wild-Pokémon-related tables to contain 16-bit IDs**

*   [x] aaaaaa123456789/pokecrystal16#8 add `inc hl` before this line: https://github.com/aaaaaa123456789/pokecrystal16/blob/expand-move-ID/engine/items/item_effects.asm#L974

### **Convert miscellaneous Pokémon IDs in ROM to 16-bit, 2**

*   [x] aaaaaa123456789/pokecrystal16#10 add `ld [wNamedObjectIndex], a` after this line: [https://github.com/aaaaaa123456789/pokecrystal16/blob/expand-move-ID/engine/pokegear/radio.asm#L1616](https://github.com/aaaaaa123456789/pokecrystal16/blob/expand-move-ID/engine/pokegear/radio.asm#L1616)

### Use indirect pointers for some structures (base data, evolutions and …

*   [x] aaaaaa123456789/pokecrystal16#5 Delete this line: [https://github.com/aaaaaa123456789/pokecrystal16/blob/expand-move-ID/engine/battle/core.asm#L3355](https://github.com/aaaaaa123456789/pokecrystal16/blob/expand-move-ID/engine/battle/core.asm#L3355)

### **Fix several miscellaneous move lists to use 16-bit indexes**

*   [x] aaaaaa123456789/pokecrystal16#10 add `ld [wNamedObjectIndex], a` after this line:  https://github.com/aaaaaa123456789/pokecrystal16/blob/expand-move-ID/engine/pokegear/radio.asm#L1637

**Comment by vulcandth** [comment]
Complete.
